  development:
    adapter: postgresql
    encoding: unicode
    database: airbnbclone_dev
    pool: 5
    host: localhost
    port: 5432

  test:
    adapter: postgresql
    encoding: unicode
    database: airbnbclone_test
    pool: 5
    host: localhost
    port: 5432